DefenseSimulator/Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DefenseSimulator.Data;
using DefenseSimulator.Models;
using DefenseSystem.Data.Models;


namespace DefenseSimulator.Controllers
{
    public class ResponsesController : Controller
    {
        private readonly DefenseSimulatorContext _context;

        public ResponsesController(DefenseSimulatorContext context)
        {
            _context = context;
        }

        // GET: Responses
        public async Task<IActionResult> Index()
        {
            var defenseSimulatorContext = _context.Response.Include(r => r.Threat);
            return View(await defenseSimulatorContext.ToListAsync());
        }

        // GET: Responses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _context.Response
                .Include(r => r.Threat)
                .FirstOrDefaultAsync(m => m.ResponseId == id);
            if (response == null)
            {
                return NotFound();
            }

            return View(response);
        }

        // GET: Responses/Create
        public IActionResult Create(int? threatId)
        {
            if (threatId == null)
            {
                ViewBag.ResponseStatuses = EnumServices.GetEnumSelectList<ResponseStatus>();
                ViewBag.CounterTypes = EnumServices.GetEnumSelectList<CounterType>();
                ViewData["ThreatId"] = new SelectList(_context.Threat, "ThreatId", "ThreatId");
                return View();
            }
            
            ViewBag.ResponseStatuses = EnumServices.GetEnumSelectList<ResponseStatus>();
            ViewBag.CounterTypes = EnumServices.GetEnumSelectList<CounterType>();
            SelectList threatIdList = new SelectList(_context.Threat.Where(m => m.ThreatId == threatId && m.IsActive), "ThreatId", "ThreatId");
            if (!threatIdList.Any())
            {
                return NotFound();
            }
            ViewData["ThreatId"] = threatIdList;
            return View();
        }

        // POST: Responses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ResponseId,ThreatId,LaunchTime,InterceptTime,ResponseType,Status")] Response response)
        {
            ModelState.Remove("Threat");
            if (ModelState.IsValid)
            {
                _context.Add(response);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewBag.ResponseStatuses = EnumServices.GetEnumSelectList<ResponseStatus>();
            ViewBag.CounterTypes = EnumServices.GetEnumSelectList<CounterType>();
            ViewData["ThreatId"] = new SelectList(_context.Threat, "ThreatId", "ThreatId", response.ThreatId);
            return View(response);
        }

        // GET: Responses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _context.Response.FindAsync(id);
            if (response == null)
            {
                return NotFound();
            }
            ViewData["ThreatId"] = new SelectList(_context.Threat, "ThreatId", "Origin", response.ThreatId);
            return View(response);
        }

        // POST: Responses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ResponseId,ThreatId,LaunchTime,InterceptTime,ResponseType,Status")] Response response)
        {
            if (id != response.ResponseId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(response);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ResponseExists(response.ResponseId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ThreatId"] = new SelectList(_context.Threat, "ThreatId", "Origin", response.ThreatId);
            return View(response);
        }

        // GET: Responses/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var response = await _context.Response
                .Include(r => r.Threat)
                .FirstOrDefaultAsync(m => m.ResponseId == id);
            if (response == null)
            {
                return NotFound();
            }

            return View(response);
        }

        // POST: Responses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var response = await _context.Response.FindAsync(id);
            if (response != null)
            {
                _context.Response.Remove(response);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ResponseExists(int id)
        {
            return _context.Response.Any(e => e.ResponseId == id);
        }
    }
}

DefenseSimulator/Controllers/SoldierController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DefenseSimulator.Data;
using DefenseSimulator.Models;
namespace DefenseSimulator.Controllers
{
    public class SoldierController : Controller

    {
        private readonly DefenseSimulatorContext _context;

        public SoldierController(DefenseSimulatorContext context)
        {
            _context = context;
        }

        // GET: Threats
        public async Task<IActionResult> Index()
        {
            var defenseSimulatorContext = _context.Threat.Include(t => t.Weapon);
            return View(await defenseSimulatorContext.ToListAsync());
        }

        

    }
}

DefenseSimulator/Views/Soldier/Index.cshtml
@model IEnumerable<DefenseSimulator.Models.Threat>

@{
    ViewData["Title"] = "Soldier";
}


<h1>Soldier</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ThreatId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Origin)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LaunchTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Weapon)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsActive)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ThreatId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Origin)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LaunchTime)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Weapon.Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsActive)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ThreatId">Edit</a> |
                    @if (item.IsActive)
                    {
                        <a asp-controller="Responses" asp-action="Create" asp-route-threatId="@item.ThreatId">respond</a>
                    }
                    <a asp-action="Delete" asp-route-id="@item.ThreatId">Delete</a>
                </td>
            </tr>
        }
        <p>
            <a asp-action="Create">Create A New Threat</a>
        </p>
    </tbody>
</table>